# Generated by Django 3.2.9 on 2021-12-02 15:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntspot',
            name='geom',
        ),
        migrations.AddField(
            model_name='huntspot',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='huntspot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='huntspot',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
