# Generated by Django 3.2.9 on 2021-12-03 10:11

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211202_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntspot',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
